name: Pipeline

on:
  push:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  pipeline:
    uses: ministryofjustice/hmpps-reporting-workflows/.github/workflows/frontend_java_pipeline.yml@v1
    secrets: inherit
    with:
      enable-probation: true
      deploy-dev-on-feature-branches: true
      deploy-test-on-feature-branches: true
      deploy-preprod-on-feature-branches: true
      slack-channel: 'dpr_cicd_approvals'
      # Workflow probation defaults are MI's (hmpps-probation-mi-api)
      probation-chart-name: hmpps-dpr-tools-api-probation
      probation-release-name: hmpps-dpr-tools-api-probation
